# Generated by Django 3.1 on 2022-04-26 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preffered_name', models.CharField(max_length=255, null=True)),
                ('profilepic', models.ImageField(default='userprofiles/dp.JPG', upload_to='userprofiles')),
                ('about', models.CharField(max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('f', 'food'), ('ft', 'fitness'), ('s', 'sports'), ('c', 'cars'), ('t', 'travel'), ('h', 'health')], max_length=2)),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.userprofile')),
            ],
        ),
    ]
