# Generated by Django 3.1 on 2022-06-26 00:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(default='userprofiles/dp.JPG', max_length=255, verbose_name='userprofiles'),
        ),
    ]
