# Generated by Django 4.1.4 on 2023-07-26 19:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/abimolusi/image/upload/v1656202700/evefbujdtdnelnjkfeiz.jpg', max_length=255, verbose_name='blog_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/abigail-molusi-a8719b229/?originalSubdomain=za', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/abimolusi/image/upload/v1690024654/person_lgnirh.jpg', max_length=255, verbose_name='userprofiles'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(null=True, related_name='thevotes', to='blog.vote'),
        ),
    ]
