# Generated by Django 4.1.4 on 2023-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/abigail-molusi-a8719b229/?originalSubdomain=za'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, default='https://twitter.com/AbigailMolusi'),
        ),
    ]
