# Generated by Django 4.1.4 on 2023-07-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
    ]
