# Generated by Django 4.1.4 on 2022-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
