# Generated by Django 4.1.4 on 2023-07-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_vote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thevotes', to='blog.vote'),
        ),
    ]
