# Generated by Django 4.1.4 on 2023-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='votes',
        ),
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(null=True, related_name='thevotes', to='blog.vote'),
        ),
    ]
