# Generated by Django 4.1.4 on 2023-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_userprofile_linkedin_alter_userprofile_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_type',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
