# Generated by Django 4.1.4 on 2023-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_vote_type_vote_downvote_vote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
    ]
