# Generated by Django 4.1.4 on 2023-07-21 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_vote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(default='dist/lebza.png', max_length=255, verbose_name='userprofiles'),
        ),
    ]
