# Generated by Django 4.1.4 on 2023-07-22 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_userprofile_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Ffreerangestock.com%2Fphotos%2F101981%2Fphoto-details.html&psig=AOvVaw2Cl1AvLbC3G-tCLcMEvsyg&ust=1690109758760000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCMCEgNGTooADFQAAAAAdAAAAABAF', max_length=255, verbose_name='blog_image'),
        ),
    ]
