# Generated by Django 4.1.4 on 2023-07-22 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/abimolusi/image/upload/v1690024603/spring_kvggqe.jpg', max_length=255, verbose_name='blog_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/abimolusi/image/upload/v1690024654/person_lgnirh.jpg', max_length=255, verbose_name='userprofiles'),
        ),
    ]
