# Generated by Django 4.1.4 on 2023-07-22 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_image_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/abimolusi/image/upload/v1656202700/evefbujdtdnelnjkfeiz.jpg', max_length=255, verbose_name='blog_image'),
        ),
    ]
